name: money_canvas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 # -------- BASIC DEPENDENCIES -------- #

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  get: ^4.6.6
  intl: ^0.19.0
  firebase_storage: ^11.6.0
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  google_sign_in: ^6.2.1

 # -------- BASIC DEV DEPENDENCIES -------- #
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 # -------- LOCAL ASSETS -------- #

  assets:
    - assets/icons/
    - assets/logos/
    - assets/img/
    - assets/background/

 # -------- LOCAL FONTS -------- #

  # fonts:
  #   - family: Manga Temple
  #     fonts:
  #       - asset: assets/fonts/mangatb.ttf
  #         weight: 800
  #       - asset: assets/fonts/mangat.ttf
  #         weight: 400
  #       - asset: assets/fonts/mangati.ttf
  #         style: italic
  
