// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynJjkMpsXkwjBQyZ05ws7pGxXkL1EC4w',
    appId: '1:300246618291:web:a075f5cced55ba459f20c6',
    messagingSenderId: '300246618291',
    projectId: 'money-canvas',
    authDomain: 'money-canvas.firebaseapp.com',
    storageBucket: 'money-canvas.appspot.com',
    measurementId: 'G-ZCNEM1K6QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVChXNfKaQl83iwyyDgvNM9UVLglRqmE',
    appId: '1:300246618291:android:cf2bcb674474048a9f20c6',
    messagingSenderId: '300246618291',
    projectId: 'money-canvas',
    storageBucket: 'money-canvas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP01huOuNGc4udm2-tCqwQXNZVSbo7voU',
    appId: '1:300246618291:ios:5c31216ec9aa96269f20c6',
    messagingSenderId: '300246618291',
    projectId: 'money-canvas',
    storageBucket: 'money-canvas.appspot.com',
    androidClientId: '300246618291-s5kmohou2bn3hu53oin39qk4sikmh9d6.apps.googleusercontent.com',
    iosClientId: '300246618291-i7shd42gm4ds6jnof71ia5mbsoupmd02.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP01huOuNGc4udm2-tCqwQXNZVSbo7voU',
    appId: '1:300246618291:ios:5352c3fa9f064ea89f20c6',
    messagingSenderId: '300246618291',
    projectId: 'money-canvas',
    storageBucket: 'money-canvas.appspot.com',
    androidClientId: '300246618291-s5kmohou2bn3hu53oin39qk4sikmh9d6.apps.googleusercontent.com',
    iosClientId: '300246618291-72lavsg1ln6b8detos2g4nldqimtr0p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyCanvas.RunnerTests',
  );
}
